---
- name: instalacao do software docker
  hosts: debian
  become: true
  tasks:

    - name: instalacao do aplicativo aptitude
      apt: 
        update_cache: yes 
        name: aptitude 
        state: latest
        autoclean: yes

    - name: instalando uma lista de softwares
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools

    - name: adicionando chave pgp do ubuntu
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: adicionando o repositorio do docker
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: atualizando o apt e instalando o docker ce
      apt: 
        update_cache: yes 
        name: docker-ce 
        state: latest
