version: '3.9'

services:
  webserver:
    image: registry.docker-dca.example:5000/nginx
    hostname: webserver
    ports:
      - 80:80
    deploy:
      mode: replicated
      replicas: 4
      placement:
        constraints:
          - node.role==manager
      restart_policy:
        condition: on-failure
