---
- hosts: all
  become: yes
  tasks:
    # alterar as permissoes de um arquivo
    - name: alterando permissao.
      file:
        path: /tmp/httpd.conf
        owner: devops
        group: users
        mode: '0700'
