- hosts: all
  become: yes
  tasks:
    - name: criando usuarios
      user:
        name:  "{{ item.name }}"
        groups: "{{ item.groups }}"
        remove: "{{ item.remove}}"
        state: absent
      loop:
        - { name: 'caio', groups: 'users', remove: 'yes' }
        - { name: 'marcos', groups: 'users', remove: 'yes' }
        - { name: 'clovis', groups: 'users' , remove: 'yes' }
