---
- hosts: all
  become: yes
  tasks:
    # adicionar uma linha em um arquivo se por acaso
    # ele nao existir.
    - name: Adicionando linha
      become: yes
      become_user: devops
      lineinfile:
        path: /tmp/httpd.conf
        line: "LogLevel_debug"
        state: present
        backup: yes
