---
- hosts: all
  become: yes
  tasks:
    - name: Validando se a linha existe no arquivo
      become: yes
      become_user: devops
      tags: example1
      lineinfile:
        path: /tmp/httpd.conf
        line: "LogLevel debug"
        state: present
        backup: yes
      check_mode: yes
      register: example1out
