---
- hosts: all
  tasks:
  - name: atualizando o indice de pacotes do apt.
    become: yes
    apt:
      name: "*"
      state: latest
      update_cache: yes
      force_apt_get: yes

  - name: instalando alguns pacotes.
    become: yes
    apt:
      name: "{{ packagesdep }}"
      force_apt_get: yes
      state: latest
      update_cache: yes
    vars:
      packagesdep:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

  - name: adicionando a chave de assinatura do repositorio oficial do docker.
    apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present

  - name: adicionando o repositorio do docker.
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
      state: present

  - name: atualizando o indice de pacotes do apt.
    become: yes
    apt:
      name: "*"
      state: latest
      update_cache: yes
      force_apt_get: yes

  - name: instalando o docker
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io

  # Docker service is disabled by default
  - name: ativando o servico do docker
    systemd:
      name: docker
      enabled: yes
