---
- name: uninstall nginx
  hosts: debian
  tasks:

    - name: parando o nginx
      service:
        name: nginx
        state: stopped

    - name: removendo o nginx
      apt: 
        name: nginx 
        state: absent
        autoremove: yes
        purge: yes

    - name: apagando o html
      file:
        path: /var/www/particula.local
        state: absent

    - name: apagando o arquivo de configuraca
      file:
        path: /etc/nginx/sites-available/particula.local
        state: absent

    - name: apagando o link simbolico
      file:
        path: /etc/nginx/sites-enabled/particula.local
        state: absent
